# Generated by Django 4.1.1 on 2022-11-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('testimonio', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
